#pragma config(Sensor, S2,     kCompass,  sensorI2CHiTechnicCompass)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S1,     HTMC,                sensorI2CCustom)


//#include "hitechnic-compass.h"

#include "Includes/hitechnic-irseeker-v2.h"

int Angulo(int svalue){
	int result;
	if(svalue < 0)
		result = 128 + svalue + 128;
	else
		result = svalue;

	return result;
}

void girar(){
	motor[rightMotor] = 20;
	motor[leftMotor] = -20;
}

task main()
{
//	SensorSubType[kCompass] =
	short valor, temp;
	//const tSensors compassSensor = S2;
	//SensorSubType[kCompass] = subTypeHiTechnicCompass;
	//StartTask(taskCompassDeviceDriver);

	while(true){
		//_target = HTMCsetTarget(HTMC);
		temp = SensorValue[kCompass];
	  //temp = SensorValue[kCompass];
		valor = Angulo(temp);
		nxtDisplayTextLine(4, "Angulo: %d", valor);
		girar();
	}
}
