#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S1,     HTMC,                sensorI2CCustom)


//#include "hitechnic-compass.h"

int Angulo(int svalue){
	int result;
	if(svalue < 0) svalue = -1 * svalue;
		result = (svalue / 10) % 360;
		if (result < 0) result = (-1) * result;
		result = result + 90;
		if (result > 359) result -= 90;
		return result;

}

void girar(){
	motor[rightMotor] = 20;
	motor[leftMotor] = -20;
}

task main()
{
//	SensorSubType[kCompass] =
	short valor, temp;
	const tSensors compassSensor = S2;
	//SensorSubType[kCompass] = subTypeHiTechnicCompass;
	//StartTask(taskCompassDeviceDriver);

	while(true){
		//_target = HTMCsetTarget(HTMC);
		temp = SensorValue[compassSensor];
	  //temp = SensorValue[kCompass];
		valor = Angulo(temp);
		nxtDisplayTextLine(4, "Angulo: %d", valor);
		girar();
	}
}
