#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Revisada: 8/10...aveces no lee
//SENSORES: Ultrasonido 4  Motores B,C
//ROBOT BUSCA SALIDA
void izquierda()
{
	motor[motorC]=-20;
	motor[motorB]=20;
	eraseDisplay();
	nxtDisplayCenteredTextLine(2,"Izquierda");
	wait1Msec(500);
}

void derecha()
{
	motor[motorC]=20;
	motor[motorB]=-20;
	eraseDisplay();
	nxtDisplayCenteredTextLine(2,"Derecha");
	wait1Msec(500);
}

task main()
{
	int velocidad=0;
	int valorUltraSonico=0;
	int distancia=35;
	int ran=0;

	while(true)
	{
		valorUltraSonico=SensorValue(sonarSensor);
		nxtDisplayCenteredTextLine(0,"valor UltraSonico");
		nxtDisplayCenteredBigTextLine(2, "%d", valorUltraSonico);
		//nxtDisplayCenteredBigTextLine(2, "%d", valorUltraSonico);
		nxtDisplayCenteredTextLine(5, "Velocidad");
		nxtDisplayCenteredTextLine(7, "%d", velocidad);
		wait1Msec(100);

		if(SensorValue(sonarSensor)>50)
		{
			velocidad=(SensorValue(sonarSensor)-distancia)/5;//En realidad no se divide, pero lo prefiero...
			motor[motorC]=velocidad;
			motor[motorB]=velocidad;
		}
		else if(SensorValue(sonarSensor)<35)
		{
			ran=random(1);//valor 0/1
			if(ran==1)
				{derecha();}//1
		  else
		  	{izquierda();}//0
		}
		if(velocidad>100)
		{
			velocidad=100;//acotar la velocidad
		}
	}
}
